/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_swing_test;

import com.jniwrapper.win32.jexcel.ExcelException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_swing_test.GUI.RightPanelButton;
import javax.swing.AbstractButton;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import sun.rmi.runtime.Log;

/**
 *
 * @author sockand
 */
public class Main_Class extends javax.swing.JFrame {

    /**
     * Creates new form Main_Class
     */
    
    public static int image_index = 0;
    public static int imagenes_max = 0;
    
    Image image;
    BitMap bitMap;
    SquareMark squaremark;
    File[] files;
 
    public Main_Class() {
        initComponents();
        
        setTitle("ALGIE COUNTER");
        setSize(800, 600);
        setPreferredSize(new Dimension(800,600));
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        System.out.print("Hola");
        
          JButton b2 = new JButton("Soy boton"); 
        b2.setBounds(0, 342, 150, 30);
        //jPanel2.add(b2);
                //b1.setMnemonic(KeyEvent.VK_D);
                //b1.setActionCommand("disable");
                //jPanel1.add(b1, BorderLayout.CENTER);
                
                //javax.swing.GroupLayout jPanel1Layout2 = new javax.swing.GroupLayout(jPanel2);
                //jPanel2.setLayout(jPanel1Layout2);
                //jPanel1Layout2.setHorizontalGroup(jPanel1Layout2.createSequentialGroup()
                //.addGroup(jPanel1Layout2.createParallelGroup(GroupLayout.Alignment.LEADING))
                //.addContainerGap()
                //.addComponent(b2)
                //.addContainerGap(16, Short.MAX_VALUE)
                //);
                //jPanel1Layout2.setVerticalGroup(jPanel1Layout2.createSequentialGroup()
                //.addGroup(jPanel1Layout2.createParallelGroup(GroupLayout.Alignment.LEADING))
                //.addContainerGap()
                //.addComponent(b2)
                //.addContainerGap(16, Short.MAX_VALUE)
                //);
                
                
                //jPanel1.getLayout().addLayoutComponent("jPanel2Layout", jMenu1);
                
                
                //jPanel1.add(b2);
                System.out.println("He añadido un boton jaja");
                
                //jPanel1.revalidate();
                //jPanel1.repaint();
                //b1.requestFocusInWindow();
        
                
        pack(); 
        setVisible(true);
    }
    
    public void actualizar_imagen(){
        System.out.println("Files lenght" + files.length + " " + image_index);
        String name = files[image_index].getName();
        System.out.println("Files nombre" + name);
        bitMap = new BitMap(name);
        setImage(bitMap.getImage());
        jLabel3.setOpaque(true);
        jLabel3.setText("CELL COUNT "+ Gvar.celulas);
        repaint();
    }
    
    public void setImage (Image image1)
    {
       image = image1;
       System.out.println("ALTURAS " + image.getHeight(null));
       squaremark = new SquareMark();
       squaremark.auto_detectSquare(bitMap.mapa);
       System.out.print("Funciona?:3");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lista_imagenes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jFileChooser1.setDialogTitle("MY FILE CHOOSER");
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(119, 176, 196));

        jLabel1.setText("Hola soy un label y solo quiero ver como me muestro. "+Gvar.square_sensibility);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(212, 211, 210));

        lista_imagenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lista_imagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_imagenesActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(253, 176, 99));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lista_imagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lista_imagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem2.setText("Save");
        jMenuItem5.setMnemonic(KeyEvent.VK_S);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Load");
        jMenuItem5.setMnemonic(KeyEvent.VK_L);
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem7.setText("Export");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem6.setText("Exit");
        jMenuItem6.setMnemonic(KeyEvent.VK_E);
        jMenuItem6.setToolTipText("Exit application");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sensibility");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("6");
        buttonGroup1.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("8");
        buttonGroup1.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("10");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        buttonGroup1.add(jRadioButtonMenuItem3);
        jMenu3.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("12");
        buttonGroup1.add(jRadioButtonMenuItem4);
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        Gvar.square_sensibility = 10;
        System.out.println("Radio "+Gvar.square_sensibility);
        actualizar_imagen();
        
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void desechado(){
        File [] files = new File[2];
        System.out.println("Componentes panel: "+jPanel1.getComponentCount());
           ArrayList<JButton> botones = new ArrayList<JButton>();
           
            for(int i =0; i<files.length; i++){
                botones.add(new JButton("Soy un boton" + (i+1))); 
                System.out.println("Soy un boton" + (i+1));
                }
            
        JButton b2 = new JButton("Soy boton"); 
                //b2.setBounds(0, 342, 150, 30);
                JButton b3 = new JButton("Soy boton 2"); 
                //b3.setBounds(0, 342, 150, 30);
        //jPanel2.add(b2);
                //b1.setMnemonic(KeyEvent.VK_D);
                //b1.setActionCommand("disable");
                //jPanel1.add(b1, BorderLayout.CENTER);
                
                javax.swing.GroupLayout jPanel1Layout2 = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel1Layout2);
                
                GroupLayout.SequentialGroup jPanel1Layout2_hGroup = jPanel1Layout2.createSequentialGroup();
               
                ParallelGroup pGroup = jPanel1Layout2
                .createParallelGroup(GroupLayout.Alignment.LEADING);
                jPanel1Layout2_hGroup.addGroup(pGroup); 
                jPanel1Layout2_hGroup.addContainerGap();
                for (JButton c : botones) {
                pGroup.addComponent(c);
                }
                jPanel1Layout2_hGroup.addContainerGap(16, Short.MAX_VALUE);
                jPanel1Layout2.setHorizontalGroup(pGroup);
                
                GroupLayout.SequentialGroup jPanel1Layout2_hGroup2 = jPanel1Layout2.createSequentialGroup();
               
                ParallelGroup pGroup2 = jPanel1Layout2
                .createParallelGroup(GroupLayout.Alignment.LEADING);
                jPanel1Layout2_hGroup2.addGroup(pGroup); 
                    jPanel1Layout2_hGroup2.addContainerGap();
                for (JButton c : botones) {
                pGroup2.addComponent(c);
                jPanel1Layout2_hGroup2.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
                System.out.println(c.getText());
                }
                jPanel1Layout2_hGroup2.addContainerGap(16, Short.MAX_VALUE);
                jPanel1Layout2.setVerticalGroup(pGroup2);
                System.out.println("Componentes panel: Borrado "+jPanel1.getComponentCount());
                jPanel2.removeAll();
                
                System.out.println("Componentes panel: Borrado "+jPanel1.getComponentCount());
                jPanel2.add(new JButton("Soy boton largoo "));
                
        
    }
    
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        FileChoosing filechoosing = new FileChoosing(this);
        files = filechoosing.resultados();
        if(files!=null){
            //ImageIcon leftButtonIcon = createImageIcon("images/right.gif");
                //JButton b1 = new JButton("Soy boton"); 
                //b1.setMnemonic(KeyEvent.VK_D);
                //b1.setActionCommand("disable");
                //jPanel1.add(b1, BorderLayout.CENTER);
                //System.out.println("He añadido un boton");
            System.out.println("Componentes panel: "+jPanel1.getComponentCount());
            
            imagenes_max = files.length;
            
            String numeros[] = new String[files.length + 1];
            numeros[0]= "NO IMAGE";
            int i = 0;
            for(File c: files){
                numeros[i+1]="Image " + (i+1);
                i++;
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel( numeros );
            lista_imagenes.setModel( model );

            //Refrescamos la GUI
            this.invalidate();
            this.validate();
            this.repaint();
            System.out.println("Componentes panel: "+jPanel1.getComponentCount());
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        int returnVal = jFileChooser1.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = jFileChooser1.getSelectedFile();
        try {
          // What to do with the file, e.g. display it in a TextArea
          System.out.print("Texto: " + new FileReader( file.getAbsolutePath() ));
        } catch (IOException ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void lista_imagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_imagenesActionPerformed
        // TODO add your handling code here:
        //String fuente = lista_imagenes.getSelectedItem().toString();
        //image_index = Integer.parseInt(fuente);
        image_index = lista_imagenes.getSelectedIndex();
        System.out.println("NUMERO" + image_index);
        image_index -=1;
        if(image_index<0){image_index=0;}
        actualizar_imagen();
    }//GEN-LAST:event_lista_imagenesActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
         Gvar.square_sensibility = 8;
        System.out.println("Radio "+Gvar.square_sensibility);
        actualizar_imagen();
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
         Gvar.square_sensibility = 6;
        System.out.println("Radio "+Gvar.square_sensibility);
        actualizar_imagen();
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
        // TODO add your handling code here:
         Gvar.square_sensibility = 12;
        System.out.println("Radio "+Gvar.square_sensibility);
        actualizar_imagen();
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            // TODO add your handling code here:
            Export export = new Export();
        } catch (ExcelException ex) {
            Logger.getLogger(Main_Class.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main_Class.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Class().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JComboBox<String> lista_imagenes;
    // End of variables declaration//GEN-END:variables


public void paint (Graphics g)
    {
        super.paint(g);
        Toolkit t = Toolkit.getDefaultToolkit ();
       
        //Image imagen10 = t.getImage ("flechaizq.png");
        if(image!=null){
            int width = jPanel1.getWidth();
            int height = jPanel1.getHeight();
            System.out.println("JPanel " + height + " Imagen " + bitMap.mapa[0].length);
            //We get from bitmap the height and width of the image.
            Gvar.zoomX = (double)width/(double)bitMap.mapa.length;
            Gvar.zoomY = (double)height/(double)bitMap.mapa[0].length;
        g.drawImage (image, Gvar.desv_derecha, Gvar.desv_arriba, width, height,this);
        }
        if(squaremark!=null){
        squaremark.draw(g);
        }
    }

}
